from __future__ import annotations

from pathlib import Path


SOURCES = [
    {
        "source": "esthermall",
        "review_exists": "YES",
        "hff_scope": "YES",
        "public_access": "YES",
        "product_linkable": "YES",
        "robots_status": "NOT_CONFIRMED",
        "terms_status": "BLOCKS_CRAWLING_OR_UNAUTHORIZED_COLLECTION",
        "bot_protection": "CHALLENGE_REPORTED",
        "purchase_verified_policy": "UNKNOWN",
        "pilot_possible": "NO",
        "decision": "BLOCKED",
        "reason": "공식 약관에 크롤링 및 무단 수집 제한이 확인되어 자동수집하지 않음.",
        "url": "https://m.esthermall.co.kr/board/list.php?bdId=goodsreview",
    },
    {
        "source": "gnm_natural_quality",
        "review_exists": "YES",
        "hff_scope": "YES",
        "public_access": "YES",
        "product_linkable": "YES",
        "robots_status": "NOT_CONFIRMED",
        "terms_status": "UNCLEAR",
        "bot_protection": "CAFE24_CHALLENGE_POSSIBLE",
        "purchase_verified_policy": "UNKNOWN",
        "pilot_possible": "CONDITIONAL",
        "decision": "CONDITIONAL",
        "reason": "공개 후기와 상품 연결은 확인했지만 자동수집 정책과 챌린지 지속 여부를 추가 확인해야 함.",
        "url": "https://gnm.co.kr/",
    },
    {
        "source": "nutrione",
        "review_exists": "PARTIAL",
        "hff_scope": "YES",
        "public_access": "YES",
        "product_linkable": "YES",
        "robots_status": "NOT_CONFIRMED",
        "terms_status": "UNCLEAR",
        "bot_protection": "UNKNOWN",
        "purchase_verified_policy": "UNKNOWN",
        "pilot_possible": "CONDITIONAL",
        "decision": "CONDITIONAL",
        "reason": "공식몰 상품과 리뷰 수 표시는 확인했으나 본문·페이지네이션의 저빈도 접근성을 확인해야 함.",
        "url": "https://nutrione.co.kr/",
    },
    {
        "source": "ckd_health",
        "review_exists": "YES",
        "hff_scope": "YES",
        "public_access": "YES",
        "product_linkable": "YES",
        "robots_status": "NOT_CONFIRMED",
        "terms_status": "UNCLEAR",
        "bot_protection": "UNKNOWN",
        "purchase_verified_policy": "UNKNOWN",
        "pilot_possible": "CONDITIONAL",
        "decision": "CONDITIONAL",
        "reason": "공식 상품목록에서 상품별 리뷰 수와 건강기능식품 상품을 확인했으나 본문 수집 정책은 미확인.",
        "url": "https://ckdhcmall.co.kr/brandProductList.do?idx=43&pidx=1",
    },
    {
        "source": "nutrime",
        "review_exists": "YES",
        "hff_scope": "YES",
        "public_access": "YES",
        "product_linkable": "YES",
        "robots_status": "NOT_CONFIRMED",
        "terms_status": "UNCLEAR",
        "bot_protection": "UNKNOWN",
        "purchase_verified_policy": "UNKNOWN",
        "pilot_possible": "CONDITIONAL",
        "decision": "CONDITIONAL",
        "reason": "공개 후기 게시판에서 상품명·본문·평점·작성일이 확인되지만 약관과 자동수집 허용 범위가 불명확함.",
        "url": "https://www.nutrime.co.kr/board/?id=goods_review",
    },
    {
        "source": "lactiv",
        "review_exists": "YES",
        "hff_scope": "YES",
        "public_access": "YES",
        "product_linkable": "YES",
        "robots_status": "NOT_CONFIRMED",
        "terms_status": "UNCLEAR",
        "bot_protection": "UNKNOWN",
        "purchase_verified_policy": "NAVER_PAY_LABEL_ONLY",
        "pilot_possible": "CONDITIONAL",
        "decision": "CONDITIONAL",
        "reason": "상품 페이지에서 리뷰 본문과 상품 연결이 보이나 구매 인증은 표시 라벨 이상으로 확정하지 않음.",
        "url": "https://www.lactiv.co.kr/product/락티브-베베키즈-팝핑스타-프로바이오틱스-유산균/205/category/52/display/1/",
    },
    {
        "source": "frombio",
        "review_exists": "YES",
        "hff_scope": "YES",
        "public_access": "YES",
        "product_linkable": "PARTIAL",
        "robots_status": "NOT_CONFIRMED",
        "terms_status": "UNCLEAR",
        "bot_protection": "UNKNOWN",
        "purchase_verified_policy": "UNKNOWN",
        "pilot_possible": "CONDITIONAL",
        "decision": "CONDITIONAL",
        "reason": "공식몰 리뷰 목록과 상품명이 확인되지만 원문·평점·날짜 필드의 일괄 접근을 추가 확인해야 함.",
        "url": "https://m.frombio.co.kr/",
    },
    {
        "source": "nutridday",
        "review_exists": "PARTIAL",
        "hff_scope": "YES",
        "public_access": "YES",
        "product_linkable": "YES",
        "robots_status": "NOT_CONFIRMED",
        "terms_status": "UNCLEAR",
        "bot_protection": "UNKNOWN",
        "purchase_verified_policy": "UNKNOWN",
        "pilot_possible": "CONDITIONAL",
        "decision": "CONDITIONAL",
        "reason": "공식몰의 건기식 상품은 확인했지만 공개 후기 원문과 페이지네이션은 추가 확인이 필요함.",
        "url": "https://nutridday.com/",
    },
    {
        "source": "nutricore",
        "review_exists": "NOT_CONFIRMED",
        "hff_scope": "YES",
        "public_access": "YES",
        "product_linkable": "YES",
        "robots_status": "NOT_CONFIRMED",
        "terms_status": "UNCLEAR",
        "bot_protection": "UNKNOWN",
        "purchase_verified_policy": "UNKNOWN",
        "pilot_possible": "NO",
        "decision": "BLOCKED",
        "reason": "공식 상품 페이지는 확인했으나 공식몰 공개 리뷰 원문을 확인하지 못해 파일럿 대상으로 삼지 않음.",
        "url": "https://nutricore.co.kr/",
    },
    {
        "source": "anguk_health",
        "review_exists": "NOT_CONFIRMED",
        "hff_scope": "YES",
        "public_access": "PARTIAL",
        "product_linkable": "PARTIAL",
        "robots_status": "NOT_CONFIRMED",
        "terms_status": "UNCLEAR",
        "bot_protection": "UNKNOWN",
        "purchase_verified_policy": "UNKNOWN",
        "pilot_possible": "NO",
        "decision": "BLOCKED",
        "reason": "공식몰에서 공개 리뷰 원문을 확인하지 못했고 검색 결과는 외부 판매처 리뷰였음.",
        "url": "https://www.ahn-gook.com/",
    },
    {
        "source": "korea_eundan",
        "review_exists": "NOT_CONFIRMED",
        "hff_scope": "YES",
        "public_access": "PARTIAL",
        "product_linkable": "PARTIAL",
        "robots_status": "NOT_CONFIRMED",
        "terms_status": "UNCLEAR",
        "bot_protection": "UNKNOWN",
        "purchase_verified_policy": "UNKNOWN",
        "pilot_possible": "NO",
        "decision": "BLOCKED",
        "reason": "공식몰 리뷰 원문은 확인하지 못했고 확인된 리뷰는 외부 플랫폼 자료였음.",
        "url": "https://www.koreaeundan.com/",
    },
    {
        "source": "doctorlin",
        "review_exists": "NOT_CONFIRMED",
        "hff_scope": "YES",
        "public_access": "PARTIAL",
        "product_linkable": "PARTIAL",
        "robots_status": "NOT_CONFIRMED",
        "terms_status": "UNCLEAR",
        "bot_protection": "UNKNOWN",
        "purchase_verified_policy": "UNKNOWN",
        "pilot_possible": "NO",
        "decision": "BLOCKED",
        "reason": "공식몰 공개 리뷰 원문·상품 연결을 확인하지 못해 자동수집 후보에서 제외함.",
        "url": "https://doctorlin.com/",
    },
]


def build_report(output: Path) -> None:
    columns = [
        "source", "review_exists", "hff_scope", "public_access", "product_linkable",
        "robots_status", "terms_status", "bot_protection", "purchase_verified_policy",
        "pilot_possible", "decision", "reason",
    ]
    lines = [
        "# 국내 건강기능식품 Raw Review Source Preflight",
        "",
        "조사 기준일: 2026-09-08",
        "",
        "공개 리뷰가 보인다는 사실만으로 자동수집을 허용하지 않았다. 약관·robots·챌린지 정책이 명확하지 않은 곳은 CONDITIONAL로 두었고, 공식 리뷰 원문이 확인되지 않은 곳은 BLOCKED로 분류했다. BLOCKED Source는 우회하지 않는다.",
        "",
        "## 요약",
        f"- 조사 후보: {len(SOURCES)}곳",
        f"- GREEN: {sum(row['decision'] == 'GREEN' for row in SOURCES)}곳",
        f"- CONDITIONAL: {sum(row['decision'] == 'CONDITIONAL' for row in SOURCES)}곳",
        f"- BLOCKED: {sum(row['decision'] == 'BLOCKED' for row in SOURCES)}곳",
        "- Raw Review 자동수집 Pilot: 실행하지 않음. GREEN 후보가 없고, CONDITIONAL 후보는 약관·robots·저빈도 접근성 확인 후 별도 승인 필요.",
        "- verified_purchase: 공식 구매완료 정책 근거가 확인되지 않은 후보는 null로 처리해야 함.",
        "",
        "## 판정표",
        "| " + " | ".join(columns) + " |",
        "|" + "---|" * len(columns),
    ]
    for row in SOURCES:
        lines.append("| " + " | ".join(str(row[column]).replace("|", "\\|") for column in columns) + " |")
    lines.extend([
        "",
        "## 출처 링크",
    ])
    for row in SOURCES:
        lines.append(f"- `{row['source']}`: {row['url']}")
    lines.extend([
        "",
        "## 다음 단계",
        "1. CONDITIONAL 후보 중 한 곳을 선정해 robots.txt, 이용약관, 저빈도 단일 요청을 수동 확인한다.",
        "2. 명시적 금지·로그인·CAPTCHA·우회가 없고 제품-리뷰 연결이 확인될 때만 GREEN으로 승격한다.",
        "3. GREEN 승격 후에도 승인된 로컬 export를 `data/raw/reviews/<source>/`에 넣고 100건 파일럿을 실행한다.",
        "4. 수집 데이터에는 작성자명·닉네임·IP를 저장하지 않고, 의료효과 표현은 Facet 후보에서 제외한다.",
    ])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    build_report(Path("reports/hff_review_crawling_sources.md"))
