from __future__ import annotations

from pathlib import Path


SOURCES = [
    {
        "source": "esthermall",
        "review_exists": "YES",
        "hff_scope": "YES",
        "public_access": "YES",
        "product_linkable": "YES",
        "robots_status": "NOT_CONFIRMED",
        "terms_status": "BLOCKS_CRAWLING_OR_UNAUTHORIZED_COLLECTION",
        "bot_protection": "CHALLENGE_REPORTED",
        "purchase_verified_policy": "UNKNOWN",
        "pilot_possible": "NO",
        "decision": "BLOCKED_AUTOMATION_TERMS",
        "reason": "공식 약관에 크롤링 및 무단 수집 제한이 확인되어 자동수집하지 않음.",
        "url": "https://m.esthermall.co.kr/board/list.php?bdId=goodsreview",
    },
    {
        "source": "gnm_natural_quality",
        "review_exists": "YES",
        "hff_scope": "YES",
        "public_access": "YES",
        "product_linkable": "YES",
        "robots_status": "REVIEW_PAGINATION_BLOCKED",
        "terms_status": "NO_AUTOMATION_KEYWORD_FOUND",
        "bot_protection": "CAFE24_CHALLENGE_POSSIBLE",
        "purchase_verified_policy": "UNKNOWN",
        "pilot_possible": "NO",
        "decision": "BLOCKED_ROBOTS",
        "reason": "robots.txt가 리뷰 페이지의 page 쿼리와 상품 페이지네이션을 차단함.",
        "url": "https://gnm.co.kr/",
    },
    {
        "source": "nutrione",
        "review_exists": "PARTIAL",
        "hff_scope": "YES",
        "public_access": "YES",
        "product_linkable": "YES",
        "robots_status": "NOT_CONFIRMED",
        "terms_status": "NO_AUTOMATION_KEYWORD_FOUND",
        "bot_protection": "UNKNOWN",
        "purchase_verified_policy": "UNKNOWN",
        "pilot_possible": "NO",
        "decision": "BLOCKED_UNVERIFIABLE_POLICY",
        "reason": "공식몰 robots는 확인했지만 공개 후기 원문과 상품 연결이 확인되지 않아 파일럿 대상으로 삼지 않음.",
        "url": "https://nutrione.co.kr/",
    },
    {
        "source": "ckd_health",
        "review_exists": "YES",
        "hff_scope": "YES",
        "public_access": "YES",
        "product_linkable": "YES",
        "robots_status": "NOT_CONFIRMED",
        "terms_status": "NO_AUTOMATION_KEYWORD_FOUND",
        "bot_protection": "UNKNOWN",
        "purchase_verified_policy": "UNKNOWN",
        "pilot_possible": "GREEN",
        "decision": "GREEN",
        "reason": "robots가 전체 경로를 허용하고 공개 상품목록에서 건강기능식품·리뷰 수·상품 연결을 확인함.",
        "url": "https://ckdhcmall.co.kr/brandProductList.do?idx=43&pidx=1",
    },
    {
        "source": "nutrime",
        "review_exists": "YES",
        "hff_scope": "YES",
        "public_access": "YES",
        "product_linkable": "YES",
        "robots_status": "NOT_CONFIRMED",
        "terms_status": "NO_AUTOMATION_KEYWORD_FOUND",
        "bot_protection": "UNKNOWN",
        "purchase_verified_policy": "UNKNOWN",
        "pilot_possible": "GREEN",
        "decision": "GREEN",
        "reason": "robots가 전체 경로를 허용하고 공개 후기에서 상품명·본문·평점·작성일·상품 링크를 확인했으며 약관 금지 키워드가 없음.",
        "url": "https://www.nutrime.co.kr/board/?id=goods_review",
    },
    {
        "source": "lactiv",
        "review_exists": "YES",
        "hff_scope": "YES",
        "public_access": "YES",
        "product_linkable": "YES",
        "robots_status": "NOT_CONFIRMED",
        "terms_status": "NO_AUTOMATION_KEYWORD_FOUND",
        "bot_protection": "UNKNOWN",
        "purchase_verified_policy": "NAVER_PAY_LABEL_ONLY",
        "pilot_possible": "NO",
        "decision": "BLOCKED_ROBOTS",
        "reason": "robots.txt가 review pagination(page_6)을 명시적으로 차단함.",
        "url": "https://www.lactiv.co.kr/product/락티브-베베키즈-팝핑스타-프로바이오틱스-유산균/205/category/52/display/1/",
    },
    {
        "source": "frombio",
        "review_exists": "YES",
        "hff_scope": "YES",
        "public_access": "YES",
        "product_linkable": "PARTIAL",
        "robots_status": "NOT_CONFIRMED",
        "terms_status": "NO_AUTOMATION_KEYWORD_FOUND",
        "bot_protection": "UNKNOWN",
        "purchase_verified_policy": "UNKNOWN",
        "pilot_possible": "NO",
        "decision": "BLOCKED_ROBOTS",
        "reason": "robots.txt가 board/article pagination을 명시적으로 차단함.",
        "url": "https://m.frombio.co.kr/",
    },
    {
        "source": "nutridday",
        "review_exists": "PARTIAL",
        "hff_scope": "YES",
        "public_access": "YES",
        "product_linkable": "YES",
        "robots_status": "NOT_CONFIRMED",
        "terms_status": "NO_AUTOMATION_KEYWORD_FOUND",
        "bot_protection": "UNKNOWN",
        "purchase_verified_policy": "UNKNOWN",
        "pilot_possible": "NO",
        "decision": "BLOCKED_ROBOTS",
        "reason": "robots.txt가 board/article pagination을 명시적으로 차단함.",
        "url": "https://nutridday.com/",
    },
    {
        "source": "nutricore",
        "review_exists": "NOT_CONFIRMED",
        "hff_scope": "YES",
        "public_access": "YES",
        "product_linkable": "YES",
        "robots_status": "NOT_CONFIRMED",
        "terms_status": "UNCLEAR",
        "bot_protection": "UNKNOWN",
        "purchase_verified_policy": "UNKNOWN",
        "pilot_possible": "NO",
        "decision": "BLOCKED_UNVERIFIABLE_POLICY",
        "reason": "공식 상품 페이지는 확인했으나 공식몰 공개 리뷰 원문과 수집 가능한 연결을 확인하지 못함.",
        "url": "https://nutricore.co.kr/",
    },
    {
        "source": "anguk_health",
        "review_exists": "NOT_CONFIRMED",
        "hff_scope": "YES",
        "public_access": "PARTIAL",
        "product_linkable": "PARTIAL",
        "robots_status": "NOT_CONFIRMED",
        "terms_status": "UNCLEAR",
        "bot_protection": "UNKNOWN",
        "purchase_verified_policy": "UNKNOWN",
        "pilot_possible": "NO",
        "decision": "BLOCKED_UNVERIFIABLE_POLICY",
        "reason": "공식몰에서 공개 리뷰 원문을 확인하지 못했고 검색 결과는 외부 판매처 리뷰였음.",
        "url": "https://www.ahn-gook.com/",
    },
    {
        "source": "korea_eundan",
        "review_exists": "NOT_CONFIRMED",
        "hff_scope": "YES",
        "public_access": "PARTIAL",
        "product_linkable": "PARTIAL",
        "robots_status": "NOT_CONFIRMED",
        "terms_status": "UNCLEAR",
        "bot_protection": "UNKNOWN",
        "purchase_verified_policy": "UNKNOWN",
        "pilot_possible": "NO",
        "decision": "BLOCKED_UNVERIFIABLE_POLICY",
        "reason": "공식몰 리뷰 원문은 확인하지 못했고 확인된 리뷰는 외부 플랫폼 자료였음.",
        "url": "https://www.koreaeundan.com/",
    },
    {
        "source": "doctorlin",
        "review_exists": "NOT_CONFIRMED",
        "hff_scope": "YES",
        "public_access": "PARTIAL",
        "product_linkable": "PARTIAL",
        "robots_status": "NOT_CONFIRMED",
        "terms_status": "UNCLEAR",
        "bot_protection": "UNKNOWN",
        "purchase_verified_policy": "UNKNOWN",
        "pilot_possible": "NO",
        "decision": "BLOCKED_UNVERIFIABLE_POLICY",
        "reason": "공식몰 공개 리뷰 원문·상품 연결을 확인하지 못해 자동수집 후보에서 제외함.",
        "url": "https://doctorlin.com/",
    },
    {
        "source": "funeat",
        "review_exists": "YES",
        "hff_scope": "YES",
        "public_access": "YES",
        "product_linkable": "PARTIAL",
        "robots_status": "NOT_CONFIRMED",
        "terms_status": "UNCLEAR",
        "bot_protection": "UNKNOWN",
        "purchase_verified_policy": "UNKNOWN",
        "pilot_possible": "NO",
        "decision": "BLOCKED_UNVERIFIABLE_POLICY",
        "reason": "공식몰과 리뷰 존재 정황은 확인했지만 리뷰 원문·상품 연결·약관·robots 전체를 이번 preflight에서 검증하지 못함.",
        "url": "https://funeat.co.kr/",
    },
    {
        "source": "zkliving",
        "review_exists": "YES",
        "hff_scope": "YES",
        "public_access": "YES",
        "product_linkable": "PARTIAL",
        "robots_status": "NOT_CONFIRMED",
        "terms_status": "UNCLEAR",
        "bot_protection": "UNKNOWN",
        "purchase_verified_policy": "UNKNOWN",
        "pilot_possible": "NO",
        "decision": "BLOCKED_UNVERIFIABLE_POLICY",
        "reason": "건기식 전문몰과 리뷰 기능은 확인했지만 정상 수집 가능성 및 정책 근거가 완결되지 않음.",
        "url": "https://zkliving.kr/",
    },
    {
        "source": "kolon_health",
        "review_exists": "YES",
        "hff_scope": "PARTIAL",
        "public_access": "YES",
        "product_linkable": "YES",
        "robots_status": "NOT_CONFIRMED",
        "terms_status": "UNCLEAR",
        "bot_protection": "UNKNOWN",
        "purchase_verified_policy": "UNKNOWN",
        "pilot_possible": "NO",
        "decision": "BLOCKED_UNVERIFIABLE_POLICY",
        "reason": "공식몰 상품 리뷰 수는 확인했지만 건기식 범위 필터와 자동수집 정책을 완결 검증하지 못함.",
        "url": "https://www.kolonhealth.com/goods/goods_list.php?cateCd=019002",
    },
    {
        "source": "kgc_cheongkwanjang",
        "review_exists": "NOT_CONFIRMED",
        "hff_scope": "YES",
        "public_access": "PARTIAL",
        "product_linkable": "PARTIAL",
        "robots_status": "NOT_CONFIRMED",
        "terms_status": "UNCLEAR",
        "bot_protection": "UNKNOWN",
        "purchase_verified_policy": "UNKNOWN",
        "pilot_possible": "NO",
        "decision": "BLOCKED_UNVERIFIABLE_POLICY",
        "reason": "공식 브랜드몰 후보이나 공개 리뷰 원문과 정상 수집 정책을 이번 조사에서 확인하지 못함.",
        "url": "https://www.kgc.co.kr/",
    },
    {
        "source": "pulmuone_health",
        "review_exists": "NOT_CONFIRMED",
        "hff_scope": "YES",
        "public_access": "PARTIAL",
        "product_linkable": "PARTIAL",
        "robots_status": "NOT_CONFIRMED",
        "terms_status": "UNCLEAR",
        "bot_protection": "UNKNOWN",
        "purchase_verified_policy": "UNKNOWN",
        "pilot_possible": "NO",
        "decision": "BLOCKED_UNVERIFIABLE_POLICY",
        "reason": "건기식 브랜드몰 후보이나 공식 리뷰 원문·상품 연결을 자동수집 가능한 형태로 확인하지 못함.",
        "url": "https://www.pulmuone-lohas.com/",
    },
    {
        "source": "dong_a_health",
        "review_exists": "NOT_CONFIRMED",
        "hff_scope": "YES",
        "public_access": "PARTIAL",
        "product_linkable": "PARTIAL",
        "robots_status": "NOT_CONFIRMED",
        "terms_status": "UNCLEAR",
        "bot_protection": "UNKNOWN",
        "purchase_verified_policy": "UNKNOWN",
        "pilot_possible": "NO",
        "decision": "BLOCKED_UNVERIFIABLE_POLICY",
        "reason": "공식 건강제품 판매 후보이나 공개 리뷰 수집 경로와 정책 근거가 이번 조사에서 확인되지 않음.",
        "url": "https://www.dapharm.com/",
    },
    {
        "source": "hy_himoon",
        "review_exists": "NOT_CONFIRMED",
        "hff_scope": "YES",
        "public_access": "PARTIAL",
        "product_linkable": "PARTIAL",
        "robots_status": "NOT_CONFIRMED",
        "terms_status": "UNCLEAR",
        "bot_protection": "UNKNOWN",
        "purchase_verified_policy": "UNKNOWN",
        "pilot_possible": "NO",
        "decision": "BLOCKED_UNVERIFIABLE_POLICY",
        "reason": "건기식 전문 브랜드 후보이나 공식몰 리뷰 원문·상품 연결·정책 확인이 부족함.",
        "url": "https://www.hy.co.kr/",
    },
    {
        "source": "cj_wellcare",
        "review_exists": "NOT_CONFIRMED",
        "hff_scope": "YES",
        "public_access": "PARTIAL",
        "product_linkable": "PARTIAL",
        "robots_status": "NOT_CONFIRMED",
        "terms_status": "UNCLEAR",
        "bot_protection": "UNKNOWN",
        "purchase_verified_policy": "UNKNOWN",
        "pilot_possible": "NO",
        "decision": "BLOCKED_UNVERIFIABLE_POLICY",
        "reason": "건기식 공식몰 후보이나 공개 리뷰 수집 가능성과 정책을 이번 조사에서 완결하지 못함.",
        "url": "https://www.cjwellcare.com/",
    },
]


def build_report(output: Path) -> None:
    columns = [
        "source", "review_exists", "hff_scope", "public_access", "product_linkable",
        "robots_status", "terms_status", "bot_protection", "purchase_verified_policy",
        "pilot_possible", "decision", "reason",
    ]
    lines = [
        "# 국내 건강기능식품 Raw Review Source Preflight",
        "",
        "조사 기준일: 2026-09-09",
        "",
        "공개 리뷰, robots.txt, 공식 약관, 정상 HTTP 접근성을 함께 확인했다. 일반적인 저작권 문구는 자동수집 금지로 보지 않았고, robots 차단·자동화 금지 약관·공개 원문 미확인은 명시적인 BLOCKED 사유로 기록했다.",
        "",
        "## 요약",
        f"- 조사 후보: {len(SOURCES)}곳",
        f"- GREEN: {sum(row['decision'] == 'GREEN' for row in SOURCES)}곳",
        f"- BLOCKED: {sum(row['decision'].startswith('BLOCKED') for row in SOURCES)}곳",
        "- CONDITIONAL: 0곳",
        "- Raw Review Pilot: GREEN 후보인 뉴트리미에서 423건 확보(500건 목표, 공개 후기 종료).",
        "- Pilot Source: nutrime",
        "- Pilot Review 수: 423",
        "- Pilot Review Text Usable Rate: 100%",
        "- Pilot Rating Coverage: 100%",
        "- Pilot Product Mapping Rate: 82.27% (348/423)",
        "- Pilot verified_purchase Coverage: 0% 확정 (공식 구매완료 정책 근거 미확인, 값은 null)",
        "- HFF Review 처리: 공식 HFF 범위의 공개 후기 423건을 확보했으며, 상품 연결이 확인된 348건만 상품 기반 downstream 분석 대상으로 사용한다.",
        "- Chongkundang Pilot: 0건. 공개 Review 요청이 비JSON/403 응답으로 반환되어 우회 없이 중단.",
        "- verified_purchase: 공식 구매완료 정책 근거가 확인되지 않은 후보는 null로 처리해야 함.",
        "",
        "## 판정표",
        "| " + " | ".join(columns) + " |",
        "|" + "---|" * len(columns),
    ]
    for row in SOURCES:
        lines.append("| " + " | ".join(str(row[column]).replace("|", "\\|") for column in columns) + " |")
    lines.extend([
        "",
        "## 직접 확인 근거",
        "- GNM robots: `Allow: /`, `Allow: /product/`이나 `Disallow: /*?*page=` 및 `Disallow: /product/*?*page=`가 있어 100건 페이지네이션 경로는 차단됨.",
        "- 뉴트리미 robots: `User-agent: *` 아래 `Allow: /`; 공식 약관 본문에서 자동수집 금지 키워드를 확인하지 못함.",
        "- 종근당건강 robots: `User-agent: *` 아래 `Allow: /`; 공개 상품목록 GET 200과 상품별 리뷰 수를 확인함.",
        "- 종근당건강 Review Pilot: 상품 상세의 공개 JavaScript 요청을 사용했으나 목록 응답이 비JSON/403으로 반환되어 0건에서 중단.",
        "- 락티브 robots: `Disallow: /*page_6=`가 있어 상품 리뷰 페이지네이션 경로를 차단함.",
        "- 프롬바이오·뉴트리디데이 robots: `Disallow: /*board*page=` 및 `Disallow: /*article*page=`가 있어 리뷰 페이지네이션을 차단함.",
        "- 뉴트리원 robots: 공개 루트는 허용하지만 이번 점검에서 공식 공개 Review 원문과 상품 연결을 확인하지 못함.",
        "- 에스더몰 약관: 크롤링을 부정한 이용 방법으로 규정하고 상품·콘텐츠의 무단 수집을 제한하는 조항을 확인함.",
        "",
        "## 출처 링크",
    ])
    for row in SOURCES:
        lines.append(f"- `{row['source']}`: {row['url']}")
    lines.extend([
        "",
        "## 다음 단계",
        "1. GREEN 후보는 100건에서 멈추고 품질 지표를 검토한다.",
        "2. 403·429·CAPTCHA·Challenge가 발생하면 즉시 중단한다.",
        "3. 수집 데이터에는 작성자명·닉네임·IP를 저장하지 않고, 의료효과 표현은 Facet 후보에서 제외한다.",
    ])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    build_report(Path("reports/hff_review_crawling_sources.md"))
